version: '3'
services:
  web:
    container_name: go-markdown-server
    build: .
    ports:
      - "8080:8080"
    environment:
      PORT: 8080
    links:
      - mongo 
  mongo:
    container_name: mongo
    image: mongo
    ports: 
      - "27017:27017"