on:
    push:
      branches:
        - master
name: Test docker build
jobs:
    deploy:
        name: Build
        runs-on: ubuntu-latest
        env:
            IMAGE_NAME: docker.pkg.github.com/${{ github.repository }}/app
            IMAGE_TAG: ${{ github.sha }}

        steps:
          - name: Checkout
            uses: actions/checkout@v2

          - name: Login to GitHub Packages
            env:
                TOKEN: ${{ secrets.GITHUB_TOKEN }}
            run: |
                docker login docker.pkg.github.com -u $GITHUB_ACTOR -p $TOKEN

          - name: Images list
            run: |
                docker images

          - name: Build
            run: |
                docker build \
                -t $IMAGE_NAME-builder-stage \
                .
                docker build \
                -t $IMAGE_NAME:$IMAGE_TAG \
                -t $IMAGE_NAME:latest \
                .

          - name: Push image to GitHub Packages
            run: |
                docker push $IMAGE_NAME-builder-stage:latest
                docker push $IMAGE_NAME:latest
                docker push $IMAGE_NAME:$IMAGE_TAG

          - name: Logout
            run: |
                docker logout docker.pkg.github.com
